// <auto-generated />
using System;
using AnnouncementWebApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnnouncementWebApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.22");

            modelBuilder.Entity("AnnouncementWebApp.Models.Announcement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDateString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDateString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telegram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = "12fb670b-5248-4a43-9dd3-9af45381cd76",
                            Active = false,
                            Address = "",
                            Email = "",
                            EndDate = new DateTime(2023, 10, 29, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            EndDateString = "29.10.23",
                            FullDescription = "У неділю, 8 жовтня, в західних областях місцями передбачаються заморозки -3 градуси.\r\n\r\nБлижче до вихідних, 7-8 жовтня, прийде відчутне похолодання. Очікується поривчастий вітер, місцями з невеликими дощами.\r\n\r\nТакий прогноз озвучив синоптик Ігор Кібальчич, передає meteoprog.\r\n\r\nЗа його словами, середньодобова температура в жовтні у більшості областей опуститься нижче +15 °С.\r\n\r\n\"Друга половина наступного тижня ознаменується прохолодною, вітряною погодою, місцями з невеликими дощами та суттєвим похолоданням. Очікувані умови погоди укладаються в кліматичну норму для цього сезону та не є аномальними\", – попередив він.\r\n\r\nЗниження температури очікується 5 жовтня. До України прийде антициклон із заходу. Очікується мінлива хмарність, без опадів. Температура повітря вночі коливатиметься в межах +6…+11°С, вдень +17…+22°С.\r\n\r\n\"У п'ятницю, 6 жовтня, у зв'язку з розвитком циклонічності над країнами Балтії значно знизиться тиск і пройдуть дощі в більшості областей України, крім західних регіонів. На Лівобережжі та в південних областях помірні дощі, місцями в супроводі гроз\", – йдеться у його прогнозі.\r\n\r\nПогода у вихідні\r\n\r\nВ суботу, 7 жовтня, в західних і місцями в північних областях пройдуть невеликі короткочасні дощі. На решті території країни без істотних опадів. Температура повітря вночі +3...+8 °С, вдень +10...+15 °С.\r\n\r\nВ неділю, 8 жовтня, у західних областях місцями передбачаються заморозки -3...0 °С; вдень +7…+12 °С. Вдень істотних опадів не очікується, лише на півночі Лівобережжя місцями пройде невеликий дощ. Вітер північно-західний, 7-12 м/с, місцями пориви, 15-20 м/с. Температура повітря вночі +2...+7 °С.",
                            Name = "Різке похолодання",
                            Owner = "Артем Бабенко",
                            OwnerId = "5339b1de-f5ba-446c-a82f-1bcc3d992025",
                            Phone = "",
                            PhotoLink = "/photos/red_flower_cold_snow.jpeg",
                            ShortDescription = "У неділю, 8 жовтня, в західних областях місцями передбачаються​​​​​​​ заморозки -3 градуси. Ближче до вихідних, 7-8 жовтня, прийде відчутне похолодання. Очікується поривчастий вітер, місцями з невеликими дощами.",
                            StartDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateString = "05.10.23",
                            Tag = "Погода",
                            Telegram = "",
                            Views = 23
                        },
                        new
                        {
                            Id = "a3a012b3-495a-46a9-b0a7-df0a0345508a",
                            Active = false,
                            Address = "пр. Володимира Івасюка 37",
                            Email = "bufet-food@gmail.com",
                            EndDate = new DateTime(2023, 10, 31, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            EndDateString = "31.10.23",
                            FullDescription = "Ласощі на ланч у ресторані BUFET! Сьогодні в нашому меню - справжня гастрономічна насолода. На обід вас очікує смачне поєднання інгредієнтів:\r\n\r\n1. Запечене куряче м'ясо: Ніжне куряче філе, обсмажене до золотистої скоринки та запечене в духмяних спеціях.\r\n    \r\n2. Броколі: Свіжі квітки броколі, які відмінно доповнюють смак страви своєю ароматною текстурою.\r\n    \r\n3. Спаржева квасоля: Додайте нотку елегантності зі спаржевою квасолею, яка надає страві особливий шарм.\r\n    \r\n4. Морква: Соковита морква, нарізана тонкими колечками, для свіжості та хрусткості.\r\n    \r\n5. Солодкий перець: Солодкуватий перець, який принесе приємну солодкість та аромат.\r\n    \r\n6. Червона цибуля: Цибуля, обсмажена до золотавої карамелізації, для глибшого смаку.\r\n    \r\n7. Зелень: Соковита зелень, яка додає свіжості та аромату.\r\n    \r\n8. Кисло-солодкий соус Чилі: Неабиякий соус, який додає страві виразний смак та гострість.\r\n    \r\nЦя страва - ідеальний вибір для тих, хто цінує смачну їжу та бажає отримати комбінацію смаків та текстур. Будь ласка, завітайте до BUFET та насолоджуйтесь цим смаковитим ланчем з овочами сьогодні!",
                            Name = "Нова страва від BUFET",
                            Owner = "Артем Бабенко",
                            OwnerId = "5339b1de-f5ba-446c-a82f-1bcc3d992025",
                            Phone = "+380979242885",
                            PhotoLink = "/photos/new_lunch-ov.jpg",
                            ShortDescription = "Ланч з овочами в складі якого: Запечене куряче м’ясо, броколі, спаржева квасоля, морква, солодкий перець, червона цибуля, зелень, кисло-солодкий соус Чилі. Вже чекає на тебе у всіх BUFET.",
                            StartDate = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateString = "15.10.23",
                            Tag = "Їжа",
                            Telegram = "",
                            Views = 57
                        });
                });

            modelBuilder.Entity("AnnouncementWebApp.Models.TemporaryPhoto", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Path");

                    b.ToTable("TemporaryPhotos");
                });

            modelBuilder.Entity("AnnouncementWebApp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "5339b1de-f5ba-446c-a82f-1bcc3d992025",
                            Email = "artem@gmail.com",
                            Name = "Артем",
                            Password = "12345",
                            RegistrationDate = "01.11.23",
                            Role = "admin",
                            Surname = "Бабенко",
                            Views = 0
                        },
                        new
                        {
                            Id = "c94f74fd-65a0-4d72-b759-899518ed1e0f",
                            Email = "tom@gmail.com",
                            Name = "Том",
                            Password = "00000",
                            RegistrationDate = "01.11.23",
                            Role = "user",
                            Surname = "Томас",
                            Views = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
